modules/online_reg/controllers/ApplicationsController.php
<?php

namespace app\modules\online_reg\controllers;

use app\components\Helpers;
use app\components\ToWords;
use app\models\ContactForm;
use app\models\ImageBank;
use app\models\User;
use app\modules\feesdue\models\FeesDue;
use app\modules\logs\models\Logs;
use app\modules\online_reg\models\SchOnlineApplicationRequirements;
use app\modules\online_reg\models\StudentOnlineRegistration;
use app\modules\online_reg\models\StudentOnlineRegistrationSearch;
use app\modules\paymentscore\models\OnlineStudentAccountHistorySearch;
use app\modules\paymentscore\models\StudentAccountHistorySearch;
use app\modules\schoolcore\models\CoreSchool;
use app\modules\schoolcore\models\CoreSchoolClass;
use app\modules\schoolcore\models\CoreStudent;
use app\modules\schoolcore\models\CoreStudentSearch;
use app\modules\schoolcore\models\CoreSubject;
use app\modules\schoolcore\models\CoreSubjectSearch;
use app\modules\schoolcore\models\Events;
use app\modules\schoolcore\models\EventsSearch;
use app\modules\schoolcore\models\OnlineTest;
use app\modules\schoolcore\models\SchoolModules;
use kartik\mpdf\Pdf;
use Yii;
use yii\base\DynamicModel;
use yii\data\Pagination;
use yii\db\Exception;
use yii\db\Query;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use yii\helpers\Url;
use yii\httpclient\Client;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\UploadedFile;


if (!Yii::$app->session->isActive) {
    session_start();
}

/**
 * CoreStudentController implements the CRUD actions for CoreStudent model.
 */
class ApplicationsController extends Controller
{


    /**
     * {@inheritdoc}
     */

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }



//    }

    /**
     * Creates a view.
     * @return mixed
     */
    public function actionIndex()
    {
        if (Yii::$app->user->can('r_student')) {
            $request = Yii::$app->request;
            $searchModel = new StudentOnlineRegistration();
            $data = $searchModel->search(Yii::$app->request->queryParams);
            $dataProvider = $data['query'];
            $pages = ['pages' => $data['pages'], 'page' => $data['cpage']];

            return ($request->isAjax) ? $this->renderAjax('index', [
                'searchModel' => $searchModel, 'dataProvider' => $dataProvider, 'pages' => $pages, 'sort' => $data['sort']]) :
                $this->render('index', ['searchModel' => $searchModel,
                    'dataProvider' => $dataProvider, 'pages' => $pages, 'sort' => $data['sort']]);
        } else {
            throw new ForbiddenHttpException('No permissions to view students.');
        }

    }

    /**
     * Deletes an existing CoreStudent model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $model = CoreStudent::find()->where(['student_code' => $id])->limit(1)->one();

        if (Yii::$app->user->can('rw_student', ['sch' => $model->school_id])) {

            try {
                Logs::logEvent("Delete Student: " . $model->fullname, null, $model->id);
                Yii::$app->db->createCommand("select drop_student_details(:student)", [':student' => $id])
                    ->execute();
                return $this->redirect(['index']);
            } catch (\Exception $e) {
                $error = isset($e->errorInfo[2]) ? $e->errorInfo[2] : $e->getMessage();
                Logs::logEvent("Error on Delete Student: " . $model->fullname . "(" . $model->student_code . ")", $error, $model->id);
                \Yii::$app->session->setFlash('actionFailed', $error);
                return \Yii::$app->runAction('schoolcore/core-student/error');
            }
        } else {
            throw new ForbiddenHttpException('No permissions to delete this students.');
        }
    }
    /**
     *
     * /**
     * Updates an existing CoreStudent model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
//    public function actionUpdate($id)
//    {
//        $model = $this->findModel($id);
//
//        if ($model->load(Yii::$app->request->post()) && $model->save()) {
//            return $this->redirect(['view', 'id' => $model->id]);
//        }
//
//        return $this->render('update', [
//            'model' => $model,
//        ]);
//    }
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if (Yii::$app->user->can('rw_student', ['sch' => $model->school_id])) {
            $request = Yii::$app->request;
            $oldModel = clone $model;
            try {
                if ($model->load(Yii::$app->request->post())) {
                    $model->school_student_registration_number = trim(strtoupper($model->school_student_registration_number));
                    $model->first_name = ucwords(strtolower($model->first_name));
                    $model->middle_name = ucwords(strtolower($model->middle_name));
                    $model->last_name = ucwords(strtolower($model->last_name));
                    Yii::trace($model->last_name);
                    if ($model->save(false)) {
                        $edited = $this->diffObjects($oldModel, $model);
                        Logs::logEvent("Edited Student (" . $model->student_code . "): " . $edited, null, $model->id);
                        return $this->redirect(['view', 'id' => $model->id]);
                    }

                }
                return ($request->isAjax) ? $this->renderAjax('update', ['model' => $model]) :
                    $this->render('update', ['model' => $model]);
            } catch (\Exception $e) {
                $error = isset($e->errorInfo[2]) ? $e->errorInfo[2] : $e->getMessage();
                Logs::logEvent("Error on Update Student: " . $model->fullname . "(" . $model->student_code . ")", $error, $model->id);
                \Yii::$app->session->setFlash('actionFailed', $error);
                //return \Yii::$app->runAction('/student/error');
            }

        } else {
            throw new ForbiddenHttpException('No permissions to create or update students.');
        }

    }

    /**
     * Finds the CoreStudent model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return CoreStudent the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = StudentOnlineRegistration::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function diffObjects($oldModel, $newModel)
    {
        $newModel->date_of_birth = Date('Y-m-d', strtotime($oldModel->date_of_birth));
        $oldModel->allow_part_payments = (!$oldModel->allow_part_payments) ? 0 : 1;
        $oldModel->disability = (!$oldModel->disability) ? 0 : 1;
        $oldArray = ArrayHelper::toArray($oldModel, [], false);
        $newArray = ArrayHelper::toArray($newModel, [], false);
        $oldvalues = array_diff_assoc($oldArray, $newArray);
        $newvalues = array_diff_assoc($newArray, $oldArray);
        $edited = '';
        foreach ($oldvalues as $ok => $ov) {
            $edited .= " |<b>" . $ok . "</b> from: " . $ov . " to: " . $newvalues[$ok];
        }
        return $edited;
    }

//    protected function findReqSchModel($id)
//    {
//        if (($model = SchOnlineApplicationRequirements::findOne('school_id'=>$id)) !== null) {
//            return $model;
//        }
//
//        throw new NotFoundHttpException('The requested page does not exist.');
//    }

    public function actionViewStdSub($id)
    {

        $model = $this->findModel($id);
        $request = Yii::$app->request;

        $searchModel = new OnlineStudentAccountHistorySearch();
        $searchModel->only_received = true;
        $dataProvider = $searchModel->search($model->student_account_id, Yii::$app->request->queryParams);
        $res = ['model' => $model, 'dataProvider' => $dataProvider, 'searchModel' => $searchModel];
        return ($request->isAjax) ? $this->renderAjax('view_std_sub', $res) : $this->render('view_std_sub', $res);


    }


    public function actionViewProgress($id)
    {
        $model = $this->findModel($id);
        Yii::trace($model->has_requested_reg_prn);
        if($model->has_requested_reg_prn){
            return ((Yii::$app->request->isAjax)) ? $this->renderAjax('application_view', [
                'model' => $model  ]) :
                $this->render('application_view', ['model' => $model]);
        }
        else{
            $studentDetails = StudentOnlineRegistration::findOne(['id'=>$id]);
            return ((Yii::$app->request->isAjax)) ? $this->renderAjax('payment_options', ['studentDetails' => $studentDetails, ]) :
                $this->render('payment_options', ['studentDetails' => $studentDetails, ]);
        }





    }



    public function newModel()
    {
        // TODO: Implement newModel() method.
        return new CoreStudent();
    }

    public function createModelFormTitle()
    {
        return 'New Student';
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return
     */

    public function actionApplicationForm($id)
    {

        $request = Yii::$app->request;
        $model = new StudentOnlineRegistration();

modules/online_reg/views/applications/_applicants_files_list.php
<?PHP
use app\components\Helpers;
use yii\helpers\Url;
?>

<br>
<div class="row">
    <table class="table" >
        <thead>
        <tr><th colspan="4"><span class="lead">Requirement Files</span></th></tr>
        <tr><th> File name</th><th><div class="float-right">
                    <?php if(Yii::$app->user->can('rw_student') ): ?>View / Remove<?php endif; ?></div></th></tr>
        </thead>
        <tbody>
        <?php
        if($uploads) :
            foreach($uploads as $k=>$v):
                $name = explode( '.', $v['file_name'] );
                $ext = $name[count($name)-1];
                $target = in_array($ext, ['png', 'jpg', 'jpeg', 'gif']) ? '_blank' : '_self';
                ?>
                <tr>
                    <td><?= $v['file_name'] ?></td>
                    <td style="padding:0 20px">
                        <?php if(Yii::$app->user->can('rw_student')) : ?>
                            <div class="float-right">
                                <a style="font-size:22px;" href="<?= Url::to(['/submission/view-file', 'id'=>$v['id']]) ?>" target="<?= $target ?>"><i class="icon-arrow-down-circle text-primary"></i></a>
                            </div>
                        <?php endif; ?>

                    </td>
                </tr>
            <?php endforeach;
        else :
            ?>
            <tr><td colspan="4">No school requirements uploads provided</td></tr>
        <?php endif; ?>
        </tbody>
    </table>
</div>

modules/online_reg/views/applications/_applicants_requirements.php
<?php

use app\components\Helpers;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\Submission */

$this->title = $sch->school_name .'Requirements';
$this->params['breadcrumbs'][] = ['label' => 'Submissions', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

$header_color = '';
?>

<div class="letter">

    <div class="row">


    </div>


    <?php if (\Yii::$app->session->hasFlash('successAlert')) : ?>
        <div class="notify notify-success">
            <a href="javascript:;" class='close-notify' data-flash='successAlert'>&times;</a>
            <div class="notify-content">
                <?= \Yii::$app->session->getFlash('successAlert'); ?>
            </div>
        </div>
    <?php endif; ?>
    <?php if (\Yii::$app->session->hasFlash('viewError')) : ?>
        <div class="notify notify-danger">
            <a href="javascript:;" class='close-notify' data-flash='viewError'>&times;</a>
            <div class="notify-content">
                <?= \Yii::$app->session->getFlash('viewError'); ?>
            </div>
        </div>
    <?php endif; ?>
    <div class="submission-view">

        <div class="row" style="border-bottom: 1px solid #c5c5c5; padding-bottom: 10px; margin-top:20px">
            <div class="col-md-10" style="padding-left:10px; "><span class="lead text-uppercase"><?php echo $this->title?> - ONLINE REGISTRATION REQUIREMENTS</span></div>

            <div class="col-md-2" style="float: right">
                <?= Html::a('Continue Application', ['applications/application-form', 'id' =>$sch->id], ['class' => 'btn btn-primary']) ?>
            </div>
        </div>

        <?php if ($model): ?>
        <?= $this->render('_view_applicants_req', ['model' => $model]) ?>


        <?php if ($model->storedFiles): ?>
            <?= $this->render('_applicants_files_list', ['uploads' => $model->storedFiles]); ?>
        <?php endif; ?>
        <?php endif; ?>

        <?php if (!$model): ?>
        <div class="row" style="padding-bottom: 10px; margin-top:20px">

         <div class="col-md-10" style="padding-left:10px;color:red "><span class="lead text-uppercase">School has no requirements set</span></div>
        </div>
        <?php endif; ?>
    </div>


</div>

modules/online_reg/views/applications/_select_school.php
<?php


use app\modules\localgov\models\County;
use kartik\grid\GridView;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\JsExpression;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\schoolcore\models\Book */
/* @var $form yii\widgets\ActiveForm */

$this->title = 'Search School';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="api-page">
    <div class=" card bg-white" style="width:100%">
        <div class=" card-body book-form">

            <div class="row">


            </div>
            <?php $form = ActiveForm::begin([
                'action' => ['schools-list'],
                'method' => 'get',
                'options' => ['class' => 'formprocess'],
            ]); ?>

            <div class="col-md-12">
                <h3 style="text-align: center;
    text-decoration: underline;
    padding: 20px;
    color: #465b97;
    text-transform: uppercase;">&nbsp;<i class="fa fa-th-list"></i> <?php echo $this->title ?>&nbsp;&nbsp;&nbsp;</h3>

            </div>
            <div class="col-md-12">
                <div id="flash_message">
                    <?php if (\Yii::$app->session->hasFlash('appeal')) : ?>
                        <?= \Yii::$app->session->getFlash('appeal'); ?>
                    <?php endif; ?>
                </div>
            </div>

            <div class="row">

            </div>
            <div class="row">
                <div class="col-sm-2">

                </div>
                <div class="col-sm-4">
                    <?= $form->field($model, 'school_name', ['inputOptions' => ['class' => 'form-control input-sm']])->textInput(['placeHolder' => 'School Name'])->label(false) ?>


                </div>


                <div class="col-sm-4">
                    <div class="btn-center">
                        <div class="form-group">
                            <?= Html::submitButton('Search', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                        </div>
                    </div>
                </div>
                <div class="col-sm-2">

                </div>
                <?php ActiveForm::end(); ?>
            </div>


    <?php


    $columns = [

        'school_code',
        'school_name',
        'district_name',

        'phone_contact_1',

        [
            'label' => '',
            'value' => function ($model) {
                return Html::a('Apply', ['requirements', 'id' => $model['id']], ['class' => 'aclink']);
            },
            'format' => 'html',
        ],




    ];
    ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
//    'filterModel' => $searchModel,
        'columns' => $columns,
        'resizableColumns' => true,
//    'floatHeader'=>true,
        'responsive' => true,
        'responsiveWrap' => false,
        'bordered' => false,
        'striped' => true,
    ]); ?>


</div>
    </div>


</div>

modules/online_reg/views/applications/_view_online_application.php
<?php


use app\modules\localgov\models\County;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\JsExpression;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\schoolcore\models\Book */
/* @var $form yii\widgets\ActiveForm */

$this->title = 'Welcome to SchoolSuite Student Online Application Platform';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="api-page">
    <div class=" card bg-white" style="width:100%">
        <div class=" card-body book-form">


                <div class="col-md-12">
                    <h3 style="text-align: center;
    text-decoration: underline;
    padding: 20px;
    color: #465b97;
    text-transform: uppercase;">&nbsp;<i class="fa fa-th-list"></i> <?php echo $this->title ?>&nbsp;&nbsp;&nbsp;</h3>

                </div>


            </div>

            <div class="row" style="min-height: 100px !important;"></div>
            <div class="row" style="min-height: 100px !important;">
                <div class="col-sm-5" >


                </div>

                <div class="col-sm-6">
                    <?php  if (\Yii::$app->session->hasFlash('error')) : ?>
                        <p style="color:red">  <?= \Yii::$app->session->getFlash('error'); ?></p>
                    <?php endif; ?>
                    <?= Html::a('<i class="fa fa-upload"></i>>> SELECT A SCHOOL TO APPLY', ['/online_reg/applications/schools-list'], ['class' => 'btn_api']) ?>
                    <BR>
                    <br/>
                    <?= Html::a('<i class="fa fa-edit"></i>>> APPLICATION PROGRESS', ['/online_reg/applications/progress-check'], ['class' => 'btn_api']) ?>

                </div>

                <div class="col-sm-1" >


                </div>
            </div>
            <div class="row" style="min-height: 100px !important;"></div>


        </div>
    </div>
</div>

modules/online_reg/views/applications/application_progress.php
<?php


use app\modules\localgov\models\County;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\JsExpression;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\schoolcore\models\Book */
/* @var $form yii\widgets\ActiveForm */

$this->title = 'Application Progress';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="api-page" style="color:black">
    <div class=" card bg-white" style="width:100%">
        <div class=" card-body book-form">

            <div class="row">
                    <div class="col-md-12">
                        <div class="pic-container">
                            <div class="site-login" style="padding-top: 10px">
                                <a class="d-flex align-items-center justify-content-center" href="">
                                    <div class="sidebar-brand-icon">
                                        <?= Html::img('@web/web/img/PNG1.png', ['alt'=>'logo', 'class'=>'img-responsive']);?>

                                    </div>

                                </a>
                            </div>
                        </div>
                    </div>


            </div>


            <div class="col-md-12">
                <h3 style="text-align: center;
    text-decoration: underline;
    padding: 20px;
    color: #465b97;
    text-transform: uppercase;">&nbsp;<i class="fa fa-th-list"></i> <?php echo $this->title ?>&nbsp;&nbsp;&nbsp;</h3>

            </div>
            <div class="col-md-12">
                <div id="flash_message">
                    <?php if (\Yii::$app->session->hasFlash('business')) : ?>
                        <?= \Yii::$app->session->getFlash('business'); ?>
                    <?php endif; ?>
                </div>
            </div>

            <div class="row">

                <div class="col border-right bg-gradient-light">
                    <div class="card bg-gradient-light">
                        <div class="card-body">

                            <div class="row">
                                <div class="col">
                                    <b style="color: #000">Student Name</b>
                                </div>
                                <div class="col" style="color: #21211f">
                                    <?= ($data['first_name'] ? $data['first_name'] . ' ' . $data['last_name'] : "--") ?>
                                </div>


                            </div>
                            <hr class="style14">
                            <div class="row">
                                <div class="col">
                                    <b style="color: #000">Name of School Applied To</b>
                                </div>
                                <div class="col" style="color: #21211f">
                                    <?= ($data['school_name'] ? $data['school_name'] : "--") ?>
                                </div>


                            </div>
                            <hr class="style14">
                            <div class="row">
                                <div class="col">
                                    <b style="color: #000">Class Applied To</b>
                                </div>
                                <div class="col" style="color: #21211f">
                                    <?= ($data['class_code'] ? $data['class_code'] : "-- ") ?>
                                </div>


                            </div>
                            <hr class="style14">
                            <div class="row">
                                <div class="col">
                                    <b style="color: #000">Status</b>
                                </div>
                                <div class="col" style="color: #21211f">
                                    <p>Pending</p>
                                </div>


                            </div>
                            <hr class="style14">

                            <div class="row">
                                <div class="col">
                                    <p style="color:steelblue">Payment History</p>
                                </div>
                                <div class="col" style="color: #21211f">
                                    <p>None</p>
                                </div>
                            </div>
                            <hr class="style14">

                            <div class="row">
                                <div class="col">

                                </div>
                                <div class="col" style="color: #21211f">

                                </div>


                            </div>
                            <div class="row">
                                <div class="col">
                                    <div class="row">
                                        <div class="col">
                                            <b style="color: #000">Payment Options</b>
                                        </div>
                                    </div>


                                    <hr class="style14">

                                    <div class="row">
                                        <div class="col">
                                            <b style="color: #000">Mobile Money</b>
                                        </div>
                                        <div class="col">
                                            <b style="color: #000">Bank</b>
                                        </div>

                                    </div>
                                    <div class="row">
                                        <div class="col">
                                            <b style="color: #000">Airtel</b>
                                            <p>Dial: *185# / *165#<br>
                                                Select: Payments -> School Fees -> School Pay and follow instructions
                                            </p><br>
                                            <hr class="style14">

                                            <b style="color: #000">MTN</b>
                                            <p>Access the Airtel Money menu by Dialing *185#<br>
                                                Select School Fees <br>
                                                Select SchoolPay <br>
                                                Follow instructions <br>
                                            </p><br>
                                            <hr class="style14">

                                            <b style="color: #000">Msente</b>
                                            <p>Dial *185#<br>
                                                Choose (4) . Bills and payments<br>
                                                Choose (5). Pay School fees<br>
                                                Follow instructions <br>
                                            </p><br>
                                        </div>
                                        <div class="col">
                                            <p>School Uses <?php echo $data['bank_name'] ?></p>
                                            <p>Simply present your Application
                                                Code <?php echo $data['payment_ref_code'] ?> to the
                                                bank.</p>
                                        </div>

                                    </div>
                                    <div class="col" style="color: #21211f">
                                    </div>


                                </div>

                            </div>

                        </div>

                    </div>

                </div>
            </div>


        </div>
    </div>
</div>

<?php
$script = <<< JS
    $(document).ready(function(){
      $('.close-notify').click(function(){
          $(".notify").hide();
      });
   });
JS;
$this->registerJs($script);
?>

modules/online_reg/views/applications/index.php
<?php

use app\modules\schoolcore\models\CoreStudent;
use app\modules\schoolcore\models\CoreStudentSearch;
use kartik\export\ExportMenu;
use yii\bootstrap4\Html;
use yii\helpers\Url;
use yii\bootstrap4\LinkPager;
//use yii\widgets\LinkPager;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel app\modules\schoolcore\models\CoreStudentSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Students Information';
?>


<div class="letters">

    <h1 class="h3 mb-0 text-gray-800"><?= Html::encode($this->title) ?></h1>
    <br>


    <?php echo $this->render('_search', ['model' => $searchModel]); ?>
    <div class="row mt-3">
        <div class="pull-right">
            <?php
            echo Html::a('<i class="fa far fa-envelope"></i> Send email', ['email'], [
                'class'=>'btn btn-sm btn-info',
                'data-toggle'=>'tooltip',
                'title'=>'Send an email to all students'
            ]);
            ?>
        </div>


        <div class="pull-right">
            <?php
            echo Html::a('<i class="fa far fa-file-pdf"></i> Download Pdf', ['core-student/export-pdf', 'model' => get_class($searchModel)], [
                'class'=>'btn btn-sm btn-danger',
                'target'=>'_blank',
                'data-toggle'=>'tooltip',
                'title'=>'Will open the generated PDF file in a new window'
            ]);
            echo Html::a('<i class="fa far fa-file-excel"></i> Download Excel', ['export-data/export-excel', 'model' => get_class($searchModel)], [
                'class'=>'btn btn-sm btn-success',
                'target'=>'_blank'
            ]);
            ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="box-body table table-responsive no-padding">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th class='clink'><?= $sort->link('first_name', ['label' => 'Student Name']) ?></th>
                        <?php if (Yii::$app->user->can('rw_sch')) {
                            echo "<th class='clink'>" . $sort->link('school_name') . "</th>";
                        } ?>
                        <th class='clink'><?= $sort->link('class_code') ?></th>
                        <th class='clink'><?= $sort->link('student_phone') ?></th>
                        <th class='clink'><?= $sort->link('application_status') ?></th>
                        <th class='clink'>&nbsp;</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                    if ($dataProvider) :
                        foreach ($dataProvider as $k => $v) : ?>
                            <tr data-key="0">
                                <td><?= ($v['student_name']) ? $v['student_name'] : '<span class="not-set">(not set) </span>' ?></td>
                                <?php if (Yii::$app->user->can('rw_sch')) : ?>
                                    <td><?= ($v['school_name']) ? $v['school_name'] : '<span class="not-set">(not set) </span>' ?></td>
                                <?php endif; ?>
                                <td><?= ($v['class_code']) ? $v['class_code'] : '<span class="not-set">(not set) </span>' ?></td>
                                <td><?= ($v['student_phone']) ? $v['student_phone'] : '<span class="not-set">(not set) </span>' ?></td>
                                <td><?= ($v['application_status']) ? $v['application_status'] : '<span class="not-set">(not set) </span>' ?></td>
                                <td>
                                    <?= Html::a('<i class="fa  fa-ellipsis-h"></i>', ['/online_reg/std-online-reg/view', 'id' => $v['id']], ['class'=>'aclink']) ?>

                                </td>
                            </tr>
                        <?php endforeach;
                    else :?>
                        <tr>
                            <td colspan="8">No student found</td>
                        </tr>
                    <?php endif; ?>
                    </tbody>
                </table>
            </div>
            <?= LinkPager::widget([
                'pagination' => $pages['pages'], 'firstPageLabel' => 'First',
                'lastPageLabel'  => 'Last'
            ]); ?>

        </div>
    </div>

</div>



</div>