modules/studentreport/controllers/SocialMediaController.php
<?php

namespace app\modules\studentreport\controllers;

use app\modules\schoolcore\models\CoreSchoolClass;
use app\modules\studentreport\models\CircularSignatures;
use app\modules\studentreport\models\SchoolSocialMedia;
use kartik\mpdf\Pdf;
use Yii;
use app\modules\logs\models\Logs;

use yii\base\BaseObject;
use yii\db\Query;
use yii\helpers\Url;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * Social Media implements the CRUD actions for social Media model.
 */
class SocialMediaController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Social Media link models.
     * @return mixed
     */
    public function actionIndex()
    {
        if (!Yii::$app->user->can('r_sch'))
            throw new ForbiddenHttpException('No permissions to view schools.');

        $request = Yii::$app->request;
        $searchModel = new SchoolSocialMedia();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return ($request->isAjax) ? $this->renderAjax('index', [
            'searchModel' => $searchModel, 'dataProvider' => $dataProvider]) :
            $this->render('index', ['searchModel' => $searchModel,
                'dataProvider' => $dataProvider]);


    }
    /**
     * Displays a single Social Media link model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     * @throws \yii\base\InvalidArgumentException
     */
    public function actionView($id)
    {
        $request = Yii::$app->request;
        return ($request->isAjax) ? $this->renderAjax('view', [
            'model' => $this->findModel($id),
        ]) :
            $this->render('view', [
                'model' => $this->findModel($id),
            ]);
    }

    /**
     * Finds the Social Media link model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Social Media link the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = SchoolSocialMedia::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }


   

    /**
     * Creates a new Social Media link model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if (!Yii::$app->user->can('rw_social_media') && !Yii::$app->user->can('schoolpay_admin')) {
            throw new ForbiddenHttpException('No permission to Write or Update to a Social media links.');
        }

        $connection = Yii::$app->db;
        $transaction = $connection->beginTransaction();
        $request = Yii::$app->request;
        $model = new SchoolSocialMedia();

        try {
            if ($model->load(Yii::$app->request->post())) {

                $incoming = Yii::$app->request->post();
                $post = $incoming['SchoolSocialMedia'];

                if (\app\components\ToWords::isSchoolUser()) {
                    $model->school_id = Yii::$app->user->identity->school_id;
                }
                $model->created_by = Yii::$app->user->identity->getId();

                if ($model->save(false)) {
                    Logs::logEvent("Created New Social Media Link: " . $model->id, null, null);
               }


                $transaction->commit();
                return $this->redirect(['view', 'id' => $model->id], 200);

                //   }
            }
        } catch (\Exception $e) {
            Yii::trace($e);
            $transaction->rollBack();
            $model_error = isset($e->errorInfo[2]) ? $e->errorInfo[2] : $e->getMessage();;
            Logs::logEvent("Failed to new social meedia link : ", $model_error, null);
            \Yii::$app->session->setFlash('actionFailed', $model_error);

        }

        $res = ['model' => $model];
        return ($request->isAjax) ? $this->renderAjax('create', $res) : $this->render('create', $res);


    }

    public function actionUpdate($id)
    {
        $request = Yii::$app->request;

        $model = $this->findModel($id);
        if (Yii::$app->user->can('rw_social_media', ['sch' => $model->school_id])) {
            if ($model->load(Yii::$app->request->post())) {

                $post = $model->load(Yii::$app->request->post());
                Yii::trace($post);
                $transaction = SchoolSocialMedia::getDb()->beginTransaction();
                try {
                    //$newId =$this->saveUser();
                    $model->created_by = Yii::$app->user->identity->getId();
                    $model->save(false);


                    $transaction->commit();

                    return $this->redirect(['view', 'id' => $model->id]);

                } catch (\Exception $e) {
                    $transaction->rollBack();
                    $error = isset($e->errorInfo[2]) ? $e->errorInfo[2] : $e->getMessage();
                    Yii::trace('Error: ' . $error, 'Update Social Media Links ROLLBACK');
                    \Yii::$app->session->setFlash('actionFailed', $model_error);

                }

            }
            $res = ['model' => $model];
            return ($request->isAjax) ? $this->renderAjax('update', $res) : $this->render('update', $res);

        } else {
            throw new ForbiddenHttpException('No permissions to create or update students.');
        }

    }
    /**
     * Deletes an existing CoreSchoolClass model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

}

modules/studentreport/views/social-media/_form.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap4\ActiveForm */

/* @var $model \app\models\SignupForm */

use app\models\User;
use app\modules\schoolcore\models\CoreBankDetails;
use app\modules\schoolcore\models\CoreSchool;
use kartik\file\FileInput;
use kartik\password\PasswordInput;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;
use yii\helpers\Url;
use yii\web\JsExpression;
use yii\web\View;
use app\models\AuthItem;

$this->title = 'Social Media Links';
?>

<div class="container card">

    <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>
    <div class="card-body">



        <div class="row">
            <div class="col-md-8">
                <i class="fa fa-facebook-square"></i>
            </div>
                <div class="col-md-8">

                    <?= $form->field($model, 'facebook_link', ['inputOptions' => ['class' => 'form-control', 'placeholder' => 'Enter Facebook Link']])->textInput(['autocomplete' => 'off'])->label(false) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8">
                <i class="fa fa-twitter-square"></i>

            </div>
            <div class="col-md-8">
                <?= $form->field($model, 'twitter_link', ['inputOptions' => ['class' => 'form-control', 'placeholder' => 'Enter Twitter Link']])->textInput(['autocomplete' => 'off'])->label(false) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8">
                <i class="fa fa-linkedin-square"></i>

            </div>
            <div class="col-md-8">
                <?= $form->field($model, 'linkedin_link', ['inputOptions' => ['class' => 'form-control', 'placeholder' => 'Enter Linkedin Link']])->textInput(['autocomplete' => 'off'])->label(false) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8">
                <i class="fa fa-skyatlas"></i>
            </div>
            <div class="col-md-8">
                <?= $form->field($model, 'telegram_link', ['inputOptions' => ['class' => 'form-control', 'placeholder' => 'Enter Telegram Link']])->textInput(['autocomplete' => 'off'])->label(false) ?>
            </div>
        </div>

        <div class="card-footer">
            <div class="row">
                <div class="col-xm-6">
                    <?= Html::submitButton($model->isNewRecord ? 'Save' : 'Update', ['class' => 'btn btn-block btn-primary']) ?>
                </div>
                <div class="col-xm-6">
                    <?= Html::resetButton('Reset', ['class' => 'btn btn-default btn-block']) ?>
                </div>
            </div>
        </div>

    </div>
    <?php ActiveForm::end(); ?>
</div>

<?php

$script = <<< JS



$("document").ready(function(){ 
    function evaluateRecurrentVisibility() {
        if($('#user_type_select').val() === '0') {
           $('#std_div').hide()
           $('#staff_div').show()
        }else {
           $('#std_div').show() 
           $('#staff_div').hide() 
        }
}

   

evaluateRecurrentVisibility();


    //On changing user type, hide or show div controls
   $('body').on('change', '#user_type_select', function(){
       evaluateRecurrentVisibility();
   });
   
   
   
    });
   


JS;
$this->registerJs($script);
?>

modules/studentreport/views/social-media/_grades.php
<div class="container">
    <?php $i=1; ?>
    <div id="submission_Contacts">
        <div style="padding:20px 0 10px 0;" class="row">
            <div class="col no-padding-left"><span class="text-uppercase">Min</span></div>
            <div class="col no-padding-left"><span class="text-uppercase">Max</span></div>
            <div class="col no-padding-left"><span class="text-uppercase">Grade</span></div>
            <div class="col-auto no-padding-left"><span style="padding-left: 24px;">&nbsp;</span></div>
        </div>
        <?php if(is_array($model->grading) && $model->grading) :
            foreach( $model->grading as $key=>$value)  : ?>
                <div style="padding-bottom:20px;" id="<?= 'add_contact_row_'.$i ?>" class="row">
                    <div class="col no-padding-left">
                        <?php if(!$model->isNewRecord) : ?>
                            <input type="hidden" name="Grading[grading][<?= $i ?>][id]" value="<?= $value['id'] ?>">
                        <?php endif; ?>
                        <input  class="form-control" type="text" required="required"  name="Grading[grading][<?= $i;?>][min]" value="<?= $value['min']?>">
                    </div>
                    <div class="col no-padding-left">
                        <input  class="form-control" type="text" required="required"  name="Grading[grading][<?= $i;?>][max]"  value="<?= $value['contact']?>">
                    </div>
                    <div class="col no-padding-left">
                        <input  class="form-control" type="text"   name="Grading[grades][<?= $i;?>][grades]" value="<?= $value['grades']?>">
                    </div>33

                    <div class="col-auto no-padding-left">
                        <?php if($i ==1)  : ?>
                            <span class="add_contact_button" style="font-size: 27px;"><i class="icon-plus text-primary"></i></span>
                        <?php else : ?>
                            <span class="remove_contact_button" style="font-size: 27px;" data-for="<?= 'add_contact_row_'.$i ?>"><i class="icon-close text-danger"></i></span>
                        <?php endif; ?>
                    </div>
                </div>
                <?php
                $i++;
            endforeach;
        else :
            ?>
            <div style="padding-bottom:20px;" id="<?= 'add_contact_row_'.$i ?>" class="row">
                <div class="col no-padding-left">
                    <input  class="form-control" type="text" required="required" name="Grading[grading][<?= $i;?>][min]"  aria-required="true">
                </div>
                <div class="col no-padding-left ">
                    <input  class="form-control" type="text" required="required"  name="Grading[grading][<?= $i;?>][max]" >
                </div>
                <div class="col no-padding-left">
                    <input  class="form-control" type="email" name="Grading[grading][<?= $i;?>][grades]" >
                </div>


                <div class="col-auto no-padding-left">
                    <?php if($i ==1)  : ?>
                        <span class="add_contact_button" style="font-size: 27px;"><i class="icon-plus text-primary"></i></span>
                    <?php else : ?>
                        <span class="remove_contact_button" style="font-size:27px;" data-for="<?= 'add_contact_row_'.$i ?>"><i class="icon-close text-danger"></i></span>
                    <?php endif; ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>

<?php
$script = <<< JS
$("document").ready(function(){
		var row = $i;
		$('.add_contact_button').on('click', function(e){
		    e.preventDefault();
			row++;
			var new_row_html = row_html(row);
			$('div#submission_Contacts').append(new_row_html);
			return false;
			
		});
		
		$('body').on('click', '.remove_contact_button', function(e){
		    e.preventDefault();
			$('div#'+$(this).attr('data-for')).remove();
		});

		var row_html = function(rw){
            var this_html = '<div style="padding-bottom:20px;" id="add_contact_row_'+rw+'" class="row"><div class="col no-padding-left">' +
             '<input  class="form-control" type="text"  name="Grading[grading]['+rw+'][min]" >' +
              '</div><div class="col no-padding-left">' +
              '<input  class="form-control" type="text" required="required" name="Grading[grading]['+rw+'][contact]" >' +
              '</div><div class="col no-padding-left">' +
              '<input  class="form-control" type="text"  name="Grading[grading]['+rw+'][email]">' +
              '</div><div class="col-auto no-padding-left">' +
              '<span class="remove_contact_button" style="font-size:27px;" data-for="add_contact_row_'+rw+'"><i class="icon-close text-danger"></i></span>' +
              '</div></div>';

			return this_html;
		}
	});
JS;
$this->registerJs($script);
?>

modules/studentreport/views/social-media/_search.php
<?php


use app\modules\schoolcore\models\CoreSchool;
use app\modules\schoolcore\models\CoreSchoolClass;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use kartik\select2\Select2;
use yii\bootstrap4\ActiveForm;
use yii\jui\DatePicker;
use yii\web\JsExpression;
?>


<div class="container bg-white" style="width:100%;">
    <div >
        <?php $form = ActiveForm::begin([
            'action' => ['index'],
            'method' => 'get',
            'options'=>['class'=>'formprocess'],
        ]); ?>

        <div class="row" style="padding: 10px">


                <div class="col-md-6">
                    <?= $form->field($model, 'isstudent', ['inputOptions' => ['class' => 'form-control',
                        'placeholder' => 'Description',
                        'disabled' => $model->is_student,]])->dropDownList(
                        ['1' => 'Student', '0' => 'Staff'],
                        ['id' => 'user_type_select', 'prompt' => 'Select']
                    )->label(false)?>
                </div>

                <div class="col-md-6">
                    <?= $form->field($model, 'modelSearch', ['inputOptions'=>[ 'class'=>'form-control'],])->textInput(['placeHolder'=>'Search Student code or Staff Id','title' => 'Enter student code or staff Id',

                        'data-toggle' => 'tooltip',

                        'data-trigger' => 'hover',

                        'data-placement' => 'bottom'])->label(false) ?>

                </div>

            </div>
            <div><?= Html::submitButton('Search', ['class' => 'btn bg-gradient-primary']) ?></div>
        </div>
        <?php ActiveForm::end(); ?>

    </div>
</div>

modules/studentreport/views/social-media/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\modules\schoolcore\models\CoreSchool */

$this->title = 'Social Media Links';
$this->params['breadcrumbs'][] = ['label' => 'Social Media Links', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="core-school-create">
    <div class="model_titles">
        <div class="col-sm-12"><h3><i class="fa fa-check-square-o"></i>&nbsp;Create Schools Social Media Links</h3></div>
    </div>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/studentreport/views/social-media/exportPdfExcel.php
<?php
use yii\helpers\Html;
?>
<div class="student-information">
    <?php
        if($type == 'Excel') {
            echo "<table><tr> <th colspan='7'><h3> Students Datasheet</h3> </th> </tr> </table>";
        }
    ?>

    <table class="table">
        <thead>
        <tr>
            <?php if($type == 'Pdf') { echo "<th>Sr No</td>"; } ?>
            <th>Payment Code</th><th>First Name</th><th>Last Name</th><?php if(Yii::$app->user->can('rw_sch')){ echo "<th>School Name</th>"; } ?> <th>Class code</th><th>Student Email</th><th>Student Phone</th><th>&nbsp;</th></tr>
        </thead>
        <tbody>
            <?php 
            $no = 1; 
            foreach($query as $sinfo) : ?>
                <tr>
                   <?php if($type == 'Pdf') {
                            echo "<td>".$no."</td>";
                        } ?>
                    <td><?= ($sinfo['class_id']) ? $sinfo['class_id'] : '<span class="not-set">(not set) </span>' ?></td>
                    <td><?= ($sinfo['first_name']) ? $sinfo['first_name'] : '<span class="not-set">(not set) </span>' ?></td>
                    <td><?= ($sinfo['last_name']) ? $sinfo['last_name'] : '<span class="not-set">(not set) </span>' ?></td>
                    <?php if(Yii::$app->user->can('rw_sch')) : ?>
                    <td><?= ($sinfo['school_name']) ? $sinfo['school_name'] : '<span class="not-set">(not set) </span>' ?></td>
                    <?php endif; ?>
                    <td><?= ($sinfo['class_code']) ? $sinfo['class_code'] : '<span class="not-set">(not set) </span>' ?></td>
                    <td><?= ($sinfo['student_email']) ? $sinfo['student_email'] : '<span class="not-set">(not set) </span>' ?></td>
                    <td><?= ($sinfo['student_phone']) ? $sinfo['student_phone'] : '<span class="not-set">(not set) </span>'?></td>
                </tr>
                <?php $no++; ?>
            <?php endforeach; ?>
        </tbody>
        </table>

</div>

modules/studentreport/views/social-media/index.php
<?php

use kartik\export\ExportMenu;
use yii\helpers\Html;
use kartik\grid\GridView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel app\modules\schoolcore\models\CoreSchoolSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Social Media Links';
$this->params['breadcrumbs'][] = $this->title;
?>
<p style="margin-top:20px ;color:#F7F7F7">.</p>
<div class="letter">



    <?php

    $columns = [

        'facebook_link',
        'twitter_link',
        'linkedin_link',
        [
            'label' => 'School Name',
            'value' => function ($model) {
                return $model['school_name'];
            },
        ],
        'date_created',
        [

            'label' => '',
            'format' => 'raw',
            'value' => function ($model) {
                return Html::a('<i class="fa  fa-ellipsis-h"></i>', ['social-media/view', 'id' => $model['id']]);
            },
        ],
        ////
    ];
    ?>


    <div class="row" style="margin-top:20px">

        <div class="col-md-3 "><span style="font-size:20px;color:#2c3844">&nbsp;<i class="fa fa-th-list"></i> <?php echo $this->title ?></span></div>
    </div>


    <?php if (\app\components\ToWords::isSchoolUser() || Yii::$app->user->can('is_teacher')) : ?>
        <?= Html::a('Add new Social Media Link', ['create'], ['class' => 'btn btn-sm btn-primary  float-right']) ?>
    <?php endif; ?>



    <div class="mt-3">
        <div class="float-right">

        </div>

        <?= GridView::widget([
            'dataProvider'=> $dataProvider,
//    'filterModel' => $searchModel,
            'columns' => $columns,
            'resizableColumns'=>true,
//    'floatHeader'=>true,
            'responsive'=>true,
            'responsiveWrap' => false,
            'bordered' => false,
            'striped' => true,
        ]); ?>

    </div>
</div>

modules/studentreport/views/social-media/student_attendance.php
<?php

use app\modules\schoolcore\models\CoreStudent;
use app\modules\schoolcore\models\CoreStudentSearch;
use kartik\export\ExportMenu;
use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;
use yii\helpers\Url;
use yii\bootstrap4\LinkPager;
//use yii\widgets\LinkPager;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel app\modules\schoolcore\models\CoreStudentSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Students Attendance Information';
?>
<h1 class="h3 mb-0 text-gray-800"><?= Html::encode($this->title) ?></h1>
<br>

<div class="row" style="background: white">
    <?php echo $this->render('_search', ['searchModel' => $searchModel]); ?>
</div>


<div class="row mt-3">
    <div class="pull-right">
        <?php
        echo Html::a('<i class="fa far fa-envelope"></i> Send email', ['email'], [
            'class'=>'btn btn-sm btn-info',
            'data-toggle'=>'tooltip',
            'title'=>'Send an email to all students'
        ]);
        ?>
    </div>


    <div class="pull-right">
        <?php
        echo Html::a('<i class="fa far fa-file-pdf"></i> Download Pdf', ['core-student/export-pdf', 'model' => get_class($searchModel)], [
            'class'=>'btn btn-sm btn-danger',
            'target'=>'_blank',
            'data-toggle'=>'tooltip',
            'title'=>'Will open the generated PDF file in a new window'
        ]);
        echo Html::a('<i class="fa far fa-file-excel"></i> Download Excel', ['export-data/export-excel', 'model' => get_class($searchModel)], [
            'class'=>'btn btn-sm btn-success',
            'target'=>'_blank'
        ]);
        ?>
    </div>

</div>




<div class="row">
    <div class="col-md-12">
        <div class="box-body table table-responsive no-padding">
            <table class="table table-striped">
                <thead>
                <?php
                $x=1;
                ?>
                <tr>
                    <th></th>
                    <th class='clink'><?= $sort->link('date_rollcalled') ?></th>
                    <th class='clink'>Roll Called By</th>
                    <th class='clink'>Class</th>
                    <th class='clink'>Subject</th>
                    <th class='clink'><?= $sort->link('student_code') ?></th>
                    <th class='clink'><?= $sort->link('first_name', ['label' => 'Student Name']) ?></th>
                    <th class='clink'><?= $sort->link('school_student_registration_number', ['label' => 'Reg No.']) ?></th>
                    <th class='clink'>Attendance</th>


                </tr>
                </thead>
                <tbody>
                <?php

                if ($dataProvider) :
                    foreach ($dataProvider as $k => $v) : ?>
                        <tr data-key="0">
                            <td><?php echo $x++?></td>
                            <td>
                                <?= ($v['date_rollcalled']) ? $v['date_rollcalled'] : '<span class="not-set">(not set) </span>' ?></td>
                            </td>
                            <td>
                                <?= ($v['username']) ? $v['username'] : '<span class="not-set">(not set) </span>' ?></td>
                            </td>
                            <td>
                                <?= ($v['class_code']) ? $v['class_code'] : '<span class="not-set">(not set) </span>' ?></td>
                            </td>
                            <td>
                                <?= ($v['subject_name']) ? $v['subject_name'] : '<span class="not-set">(not set) </span>' ?></td>
                            </td>
                            <td class="clink">

                                <?= ($v['student_code']) ? '<a href="' . Url::to(['/schoolcore/core-student/view', 'id' => $v['id']]) . '">' . $v['student_code'] . '</a>' : '<span class="not-set">(not set) </span>' ?></td>

                            <td>

                                <?= ($v['student_name']) ? $v['student_name'] : '<span class="not-set">(not set) </span>' ?></td>

                            <td>

                                <?= ($v['school_student_registration_number']) ? $v['school_student_registration_number'] : '<span class="not-set">(not set) </span>' ?></td>

                            <td>
                                <?= ($v['student_attended']) ? "Present" : "Absent" ?>

                            </td>

                        </tr>
                    <?php endforeach;
                else :?>
                    <tr>
                        <td colspan="8">No student found</td>
                    </tr>
                <?php endif; ?>
                </tbody>
            </table>
        </div>


    </div>
</div>

modules/studentreport/views/social-media/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\modules\schoolcore\models\CoreSchool */

$this->title = 'Update Core School: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Core Schools', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="core-school-update">

    <div class="model_titles">
        <div class="col-sm-12"><h3><i class="fa fa-check-square-o"></i>&nbsp;Update Grades for Class</h3></div>
    </div>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/studentreport/views/social-media/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\modules\schoolcore\models\CoreGrades */

$this->title = "Social Media Links ";
$this->params['breadcrumbs'][] = ['label' => 'Social Media Links', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

$school =\app\modules\schoolcore\models\CoreSchool::findOne(['id'=>Yii::$app->user->identity->school_id]);
Yii::trace($school);
\yii\web\YiiAsset::register($this);
?>
<p style="color: #F1F4F6">Social Media Links</p>

<div class="letter">

    <?php if (\Yii::$app->session->hasFlash('stuAlert')) : ?>
        <div class="notify notify-success">
            <a href="javascript:" class='close-notify' data-flash='stuAlert'>&times;</a>
            <div class="notify-content">
                <?= \Yii::$app->session->getFlash('stuAlert'); ?>
            </div>
        </div>
    <?php endif; ?>
    <?php if (\Yii::$app->session->hasFlash('viewError')) : ?>
        <div class="notify notify-danger">
            <a href="javascript:" class='close-notify' data-flash='viewError'>&times;</a>
            <div class="notify-content">
                <?= \Yii::$app->session->getFlash('viewError'); ?>
            </div>
        </div>
    <?php endif; ?>
    <div class="core-school-view">

        <div class="row">

            <div class="col-sm-10 "><span style="font-size:20px">&nbsp;<i
                            class="fa fa-th-list"></i> <?php echo $this->title ?> for <?= $school['school_name']?></span></div>
            <div class="col-sm-2">
                <?= Html::a('<i class="fa fa-edit" >Update</i>', ['update', 'id' => $model->id], ['class' => 'btn btn-sm btn-primary']) ?>
                <?= Html::a('<i class="fa fa-trash" >Delete</i>', ['delete', 'id' => $model->id], [
                    'class' => 'btn btn-sm btn-danger',
                    'data' => [
                        'confirm' => 'Are you sure you want to delete this item?',
                        'method' => 'post',
                    ],
                ]) ?>
            </div>
        </div>


        <div class="row">

            <div class="col border-right bg-gradient-light">
                <div class="card bg-gradient-light">
                    <div class="card-body">


                        <div class="row">
                            <div class="col">
                                <b style="color: #000"> <i class="fa fa-facebook-square"></i>
                                </b>
                            </div>
                            <div class="col" style="color: #21211f">
                                <?= ($model->facebook_link) ? ($model->facebook_link) : "--" ?>
                            </div>


                        </div>
                        <hr class="style14">


                        <div class="row">
                            <div class="col">
                                <b style="color: #000"> <i class="fa fa-twitter-square"></i></b>
                            </div>
                            <div class="col" style="color: #21211f">
                                <?= ($model->twitter_link) ? $model->twitter_link : "--" ?>
                            </div>


                        </div>

                        <hr class="style14">

                        <div class="row">
                            <div class="col">
                                <i class="fa fa-linkedin-square"></i>
                            </div>
                            <div class="col" style="color: #21211f">
                                <?= ($model->linkedin_link) ? $model->linkedin_link : "--" ?>
                            </div>


                        </div>

                        <hr class="style14">


                    </div>
                </div>
            </div>
        </div>
    </div>


</div>