modules/dissertation/models/Dissertation.php
<?php

namespace app\modules\dissertation\models;

use app\modules\schoolcore\models\CoreStudent;
use Yii;
use yii\db\Query;
use yii\web\NotFoundHttpException;
use yii\base\NotSupportedException;
use yii\data\ActiveDataProvider;
use yii\data\Pagination;

/**
 * This is the model class for table "dissertation".
 *
 * @property int $id
 * @property string $title
 * @property int $student_id
 * @property string|null $degree_program
 * @property string|null $submission_date
 * @property string $department
 * @property string $summary
 * @property int $supervisor
 * @property int $school_id
 * @property int|null $created_by
 */
class Dissertation extends \yii\db\ActiveRecord
{   
    public $uploads;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'dissertation';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title', 'student_id', 'department', 'summary', 'supervisor', 'school_id'], 'required'],
            [['title', 'degree_program', 'department', 'summary','notes'], 'string'],
            [['student_id', 'school_id', 'created_by'], 'default', 'value' => null],
            [['student_id', 'school_id', 'created_by', 'supervisor','approved_by','item'], 'integer'],
            [['uploads'], 'file', 'extensions' => 'png, jpg,pdf, doc, docx', 'maxFiles' => 10],
            [['submission_date'], 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'student_id' => 'Student ID',
            'degree_program' => 'Degree Program',
            'submission_date' => 'Submission Date',
            'department' => 'Department',
            'summary' => 'Summary',
            'supervisor' => 'Supervisor',
            'school_id' => 'School ID',
            'created_by' => 'Created By',
        ];
    }


    public function getStoredFiles(){
        $files = (new Query())->select(['id', 'file_name'])->from('dissertation_uploads')
            ->where(['submission_id'=>$this->id]);
        return $files->all();
    }

    public function saveUploads()
    {

        if (is_array($this->uploads) && $this->uploads) {

            foreach ($this->uploads as $file) {
                $upload = new DissertationUploads();
                $fname = $file->baseName . '.' . $file->extension;

                $tmpfile_contents = file_get_contents($file->tempName);
                Yii::trace($tmpfile_contents);
                $upload->submission_id = $this->id;
                $upload->file_name = $fname;
                $upload->file_data = base64_encode($tmpfile_contents);
                $upload->save(false);
                Yii::trace('Saved file ' . $file->baseName);

            }
        }
    }


    public function saveAndUpdateUploads()
    {
        Yii::trace($this->uploads);
        if (is_array($this->uploads) && $this->uploads) {
            //ofcourse first delete old uploads n then upload the new ones
            //simplest way to effect file uploads


            foreach ($this->uploads as $file) {
                $upload = new DissertationUploads();
                $fname = $file->baseName . '.' . $file->extension;

                $tmpfile_contents = file_get_contents($file->tempName);
                Yii::trace($tmpfile_contents);
                $upload->submission_id = $this->id;
                $upload->file_name = $fname;
                $upload->file_data = base64_encode($tmpfile_contents);
                $upload->save(false);
                Yii::trace('Saved file ' . $file->baseName);

            }
        }
    }

    public function getStdName()
    {
        return $this->hasOne(CoreStudent::className(), ['id' => 'student_id']);
    }

}

modules/dissertation/controllers/DissertationController.php
<?php

namespace app\modules\dissertation\controllers;

use Yii;
use app\controllers\BaseController;
use yii\db\Exception;
use yii\filters\AccessControl;
use yii\web\Response;
use yii\filters\VerbFilter;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\helpers\HtmlPurifier;
use yii\helpers\ArrayHelper;
use yii\db\Query;

use app\models\User;
use app\modules\logs\models\Logs;
use app\modules\dissertation\models\Dissertation;
use app\modules\dissertation\models\DissertationSearch;
use app\modules\dissertation\models\DissertationUploads;
use app\modules\schoolcore\models\CoreStudent;
use yii\web\UploadedFile;




if (!Yii::$app->session->isActive) {
    session_start();
}


/**
 * DissertationController that handles the lesson plan/syllabus
 */
class DissertationController extends BaseController
{
     

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Display the dissertation
     */
    public function actionIndex(){
        
        $request = Yii::$app->request;

        if (empty(Yii::$app->user->identity) ) {
             
            return \Yii::$app->runAction('/site/login');
        }


        $searchModel = new DissertationSearch();
        $searchParams = Yii::$app->request->queryParams;
        $schoolId = Yii::$app->user->identity->school_id;
        $searchParams['school_id'] = $schoolId;
        $searchParams['active'] = true;
        Yii::trace($searchParams);

        $studentDetail = $this->determineIfStudent();
        if($studentDetail && $studentDetail['is_student'] == true){
            $studentId = $studentDetail['student_id'];
            $searchParams['student_id'] =  $studentId;
            $dataProvider = $searchModel->search($searchParams);

        }else{
            //school admin has access to all dissertations
            $dataProvider = $searchModel->search($searchParams);
        }

        return ($request->isAjax) ? $this->renderAjax('index', [
                     'searchModel' => $searchModel, 'dataProvider' => $dataProvider]) :
                $this->render('index', ['searchModel' => $searchModel,
                            'dataProvider' => $dataProvider]);
    }


    //you must override these methods to use BaseControler.
    /**
     * Creates a new Dissertation model
     * @return Dissertation
     */
    public function newModel()
    {
        $model = new Dissertation();
        $model->created_by = Yii::$app->user->identity->getId();
        return $model;
    }

    /**
     * @return DissertationSearch
     */
    public function newSearchModel()
    {
        $searchModel = new DissertationSearch();
        return $searchModel;
    }

    public function createModelFormTitle()
    {
        return 'Create Dissertation';
    }

    /**
     * searches fields.
     * @return mixed
     */
    public function actionSearch()
    {
        $searchModel = $this->newSearchModel();
        $allData = $searchModel->search(Yii::$app->request->queryParams);

        $dataProvider = $allData['dataProvider'];
        $columns = $allData['columns'];
        $searchForm  = $allData['searchForm'];
        $res = ['dataProvider'=>$dataProvider, 'columns'=>$columns,'searchModel'=>$searchModel,'searchForm'=>$searchForm];
        // return $request->isAjax ? $this->renderAjax('card_summary', $res)

        return $this->render('@app/views/common/grid_view', $res);
    }


     /**
     * Creates a new Dissertation model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     *  @return mixed
     */
    public function actionCreate()
    {   

//        if (Yii::$app->user->can('non_student')) {
//            throw new ForbiddenHttpException('No permission to create or upload the dissertation / publications. Only students are authorised to do so');
//        }

        if (empty(Yii::$app->user->identity) ) {
            return \Yii::$app->runAction('/site/login');
        }

        $connection = Yii::$app->db;
        $transaction = $connection->beginTransaction();
        $request = Yii::$app->request;
        $model = new Dissertation();

         try {
            if ($model->load(Yii::$app->request->post())) {

                $model->created_by = Yii::$app->user->identity->getId();
                //if u own the school
                $schoolId = Yii::$app->user->identity->school_id;
                $model->school_id = $schoolId;

                $studentDetail = $this->determineIfStudent();

                if($studentDetail && $studentDetail['is_student'] == true){
                     $model->student_id = $studentDetail['student_id'];
                }else{
                    throw new ForbiddenHttpException('No student details found');
                   // $res = ['model' => $model];
                   // return ($request->isAjax) ? $this->renderAjax('create', $res) : $this->render('create', $res);


                }

                $model->uploads = UploadedFile::getInstances($model, 'uploads');

                if( $model->save(false) ){
                    Logs::logEvent("Created Dissertation : " . $model->id, null, null);
                    $model->saveUploads(); //fix the upload issue here                   
                }
                 
                $transaction->commit();
                
                return $this->redirect(['view', 'id' => $model->id]);

            }
        } catch (\Exception $e) {
            Yii::trace($e);
            $transaction->rollBack();
            $error = isset($e->errorInfo[2]) ? $e->errorInfo[2] : $e->getMessage();

             \Yii::$app->session->setFlash('viewError', $error);
            Logs::logEvent("Failed create new dissertation : ", $error, null);
        }

        $res = ['model' => $model];
        return ($request->isAjax) ? $this->renderAjax('create', $res) : $this->render('create', $res);

    }


    /**
     * Displays a single Dissertation  model.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */

    public function actionView($id)
    {  
        // if (!Yii::$app->user->can('r_timetable') || \Yii::$app->user->can('non_student') )
        //     throw new ForbiddenHttpException('No permissions to view schools timetable');
        
        if (empty(Yii::$app->user->identity) ) {
             
            return \Yii::$app->runAction('/site/login');
        }
        
        $model = $this->findModel($id);



        $responseData = [
            'model' => $model
        ];

        return ((Yii::$app->request->isAjax)) ? 
            $this->renderAjax('view',$responseData) 
                :
            $this->render('view', $responseData);


    }


    /**
     * Updates an existing Dissertation model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {   
        if (Yii::$app->user->can('non_student')) {
            throw new ForbiddenHttpException('No permission to Update the dissertation/publication. Only students are authorised to do so');
        }

        $model = $this->findModel($id);

        try {
            if ($model->load(Yii::$app->request->post())) {

                $model->uploads = UploadedFile::getInstances($model, 'uploads');

                if( $model->save(false) ){
                    Logs::logEvent("Updated the Dissertation: " . $model->id, null, null);
                    //$model->saveAndUpdateUploads(); //ofcourse first delete old uploads n upload new ones
                    $model->saveUploads();                   
                }
                return $this->redirect(['view', 'id' => $model->id]);

            }
        } catch (Exception $e) {
            $error = isset($e->errorInfo[2]) ? $e->errorInfo[2] : $e->getMessage();
            Yii::trace($error);
        }


        //$model->date_created = ($model->date_created)? date('Y-m-d', strtotime($model->date_created)) : '' ;

        return $this->render('update', [
            'model' => $model,
        ]);
    }


     /**
     * View/Download Document
     * @param integer $id
     * @return mixed
     */
    public function actionViewFile($id){
        $response = Yii::$app->response;
        $model = DissertationUploads::find()->where(['id' => $id])->limit(1)->one();
        $name = explode('.', $model->file_name);
        $ext = $name[count($name) - 1];
        $disposition = in_array($ext, ['png', 'jpg', 'jpeg', 'gif', 'pdf']) ? 'inline;' : 'attachment;';
        $response->format = \yii\web\Response::FORMAT_RAW;
        if ($ext == 'pdf') {
            $response->headers->set('Content-type', 'application/pdf');
        } else {
            $response->headers->set('Content-type', $ext);
        }
           
        $response->headers->set('Content-Disposition', $disposition . ' filename="' . $model->file_name . '"');

        $response->content = base64_decode($model->file_data);

        return $response;
    }

   
     /**
     * Remove the uploaded file / Document
     * @param integer $id
     * @return mixed
     */
    public function actionRemoveFile($id){
        //allow only the student to delete the file
        if (!\Yii::$app->user->can('non_student')) {

modules/dissertation/views/dissertation/_approval_buttons.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>



    <?php
    $form = ActiveForm::begin([
        'action' => ['do'],
        'method' => 'post',
        'options' => ['class' => 'formprocess', 'id' => 'workflowActionsForm']
    ]); ?>
    <div class="col-md-12 ">
        <?= $form->field($actionModel, 'notes')->textarea()->label('Approval / Rejection Notes') ?>
        <input type="hidden" name="Dissertation[item]" value="1" />

    </div>

    <div class="col-md-12">
        <?= Html::button('Approve <i class="fa fa-check-circle"></i>', ['class' => 'btn btn-success',
            'onclick' => 'confirmAndSubmitWorkflow("workflowActionsForm", "Are you sure you want to approve this dissertation, action can not be undone", "do?action=approve")',
            'value' => 'Approve', 'name' => 'submit']) ?>

        <?= Html::button('Reject <i class="fa fa-times-circle"></i>', ['class' => 'btn btn-danger pull-right',
            'onclick' => 'confirmAndSubmitWorkflow("workflowActionsForm", "Are you sure you want to reject this dissertation, action can not be undone", "do?action=reject")',
            'value' => 'Reject', 'name' => 'submit']) ?>

    </div>
    <?php ActiveForm::end(); ?>
<div style="clear: both"></div>

modules/dissertation/views/dissertation/_form.php
<?php

use app\models\User;
use app\modules\planner\models\CoreStaff;
use app\modules\schoolcore\models\CoreTerm;
use kartik\select2\Select2;
use yii\bootstrap4\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\JsExpression;
use yii\web\View;
use kartik\file\FileInput;


/* @var $this yii\web\View */
/* @var $model app\modules\schoolcore\models\CoreTerm */
/* @var $form yii\bootstrap4\ActiveForm */
?>
<div class=" row ">
    <p>All fields marked with * are required</p>


    <div class="col-md-12">
        <?= ($model->isNewRecord) ? '<h3><i class="fa fa-plus"></i> Create Dissertation</h3>' : '<h3><i class="fa fa-edit"></i> Edit Dissertation</h3>' ?>
        <hr class="l_header"></hr>
        <div class="col-md-12">
            <br/>
            <br/>
        </div>
    </div>

    <div class="col-md-12">
        <?php

        $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data'], 'action' => 'create']);

        if (!$model->isNewRecord) { //edit mode
            $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data'], 'action' => ['update', 'id' => $model->id]]);
        }

        ?>
        <div class="col-md-12">
            <div class="col-md-6">
                <?= $form->field($model, 'title', ['labelOptions' => ['style' => 'color:#041f4a']])->textInput()->label('Title *') ?>
            </div>
            <div class="col-md-6">
                <?php
                $url = Url::to(['/planner/planner/staff-list']);
                $staffInfo = empty($model->supervisor) ? '' : CoreStaff::findOne($model->supervisor);
                $selectedStaff = $staffInfo ? $staffInfo->first_name . ' ' . $staffInfo->last_name : '';


                echo $form->field($model, 'supervisor')->widget(Select2::classname(), [
                    'options' => ['multiple' => false, 'placeholder' => 'Search by firstname'],
                    'initValueText' => $selectedStaff, // set the initial display text
                    'pluginOptions' => [
                        'allowClear' => true,
                        'minimumInputLength' => 3,
                        'language' => [
                            'errorLoading' => new JsExpression("function () { return 'Waiting for results...'; }"),
                        ],
                        'style' => 'color:#041f4a',
                        'ajax' => [
                            'url' => $url,
                            'dataType' => 'json',
                            'data' => new JsExpression('function(params) { return {q:params.term}; }')
                        ],

                    ],
                ])->label('Supervisor Name *');
                ?>
            </div>


            <div class="col-md-6">
                <?= $form->field($model, 'department', ['labelOptions' => ['style' => 'color:#041f4a']])->textInput()->label('Department *') ?>
            </div>
            <div class="col-md-6">
                <?= $form->field($model, 'degree_program', ['labelOptions' => ['style' => 'color:#041f4a']])->textInput()->label('Degree Program *') ?>
            </div>


            <div class="col-md-12">
                <?= $form->field($model, 'summary', ['labelOptions' => ['style' => 'color:#041f4a']])->textarea()->label('Summary *') ?>
            </div>


            <br>


            <div class="col-md-12 text-center"><h3><i class="fa fa-check-square-o"></i>&nbsp;Attach Documents</h3></div>

            <div class="col-md-6">
                <?= $form->field($model, 'uploads[]')->widget(FileInput::classname(), [
                    'options' => ['multiple' => true],
                    'pluginOptions' => [
                        'allowedFileExtensions' => ['jpg', 'png', 'jpeg', 'pdf'],
                        'showUpload' => false,
                        'showCancel' => false,
                        'maxFileCount' => 5,
                        'fileActionSettings' => [
                            'showZoom' => false,
                        ]
                    ],
                ])->label(false);
                ?>
            </div>
            <div class="col-md-6">
                <h3>1.To upload multiple files, just select all files and then drag and drop there</h3>
                <h3>2.If you do not want to edit the uploaded files/documents, just leave it blank.. </h3>
            </div>
        </div>
        <div class="col-md-12">
            <div class="card-footer">
                <div class="row">
                    <div class="col-xm-6">
                        <?= Html::submitButton($model->isNewRecord ? 'Save' : 'Update', ['class' => 'btn btn-block btn-primary']) ?>
                    </div>
                    <div class="col-xm-6">
                        <?= Html::resetButton('Reset', ['class' => 'btn btn-default btn-block']) ?>
                    </div>
                </div>
            </div>
        </div>

        <?php ActiveForm::end(); ?>
    </div>
</div>

modules/dissertation/views/dissertation/_search.php
<?php


use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use kartik\select2\Select2;
use yii\bootstrap\ActiveForm;
use yii\web\JsExpression;
use app\modules\planner\models\CoreStaff;
use app\modules\schoolcore\models\CoreStudent;

?>



<?php $form = ActiveForm::begin([
    'action' => ['index'],
    'method' => 'get',
    'options' => ['class' => 'formprocess'],
]); ?>
<div class="row student-search">
    <div class="col-md-3">
        <?= $form->field($model, 'title', ['inputOptions' => ['class' => 'form-control input-sm']])->textInput(['placeHolder' => 'Title of dissertation'])->label(false) ?>

    </div>
    <div class="col-md-3">
        <?php
        $url = Url::to(['/planner/planner/staff-list']);
        $staffInfo = empty($model->supervisor) ? '' : CoreStaff::findOne($model->supervisor);
        $selectedStaff = $staffInfo ? $staffInfo->first_name . ' ' . $staffInfo->last_name : '';


        echo $form->field($model, 'supervisor')->widget(Select2::classname(), [
            'options' => ['multiple' => false, 'placeholder' => 'Supervisor'],
            'initValueText' => $selectedStaff, // set the initial display text
            'pluginOptions' => [
                'allowClear' => true,
                'minimumInputLength' => 3,
                'language' => [
                    'errorLoading' => new JsExpression("function () { return 'Waiting for results...'; }"),
                ],
                'ajax' => [
                    'url' => $url,
                    'dataType' => 'json',
                    'data' => new JsExpression('function(params) { return {q:params.term}; }')
                ],

            ],
        ])->label(false);
        ?>
    </div>
    <div class="col-md-3">

        <?php
        $url = Url::to(['student-list']);
        $studentInfo = empty($model->student_id) ? '' : CoreStudent::findOne($model->student_id);
        $selectedStudent = $studentInfo ? $studentInfo->first_name . ' ' . $studentInfo->last_name : '';


        echo $form->field($model, 'student_id')->widget(Select2::classname(), [
            'options' => ['multiple' => false, 'placeholder' => 'Student...'],
            'initValueText' => $selectedStudent, // set the initial display text
            'pluginOptions' => [
                'allowClear' => true,
                'minimumInputLength' => 3,
                'language' => [
                    'errorLoading' => new JsExpression("function () { return 'Waiting for results...'; }"),
                ],
                'ajax' => [
                    'url' => $url,
                    'dataType' => 'json',
                    'data' => new JsExpression('function(params) { return {q:params.term}; }')
                ],

            ],
        ])->label(false);
        ?>

    </div>
    <div class="col-md-3">

        <?= Html::submitButton('Search', ['class' => 'btn btn-info btn-sm']) ?>
    </div>

</div>
<?php ActiveForm::end(); ?>

modules/dissertation/views/dissertation/create.php
<?php

//use app\modules\schoolcore\models\CoreTerm;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\modules\schoolcore\models\CoreTerm*/

?>
<div class="core-school-class-create">
    <?php if (\Yii::$app->session->hasFlash('viewError')) : ?>
        <div class="notify notify-danger">
            <a href="javascript:;" class='close-notify' data-flash='viewError'>&times;</a>
            <div class="notify-content">
                <?= \Yii::$app->session->getFlash('viewError'); ?>
            </div>
        </div>
    <?php endif; ?>
    <div class="row">
        <?= $this->render('_form', [
            'model' => $model,
        ]) ?>
    </div>


</div>

modules/dissertation/views/dissertation/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\modules\schoolcore\models\CoreTerm*/

$this->title = 'Edit Dissertation: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Research Dissertation', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="core-school-class-update">

<?= $this->render('_form', [
    'model' => $model
]) ?>

</div>

modules/dissertation/views/dissertation/view.php
<?php

use kartik\form\ActiveForm;
use kartik\typeahead\TypeaheadBasic;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap4\LinkPager;
//use yii\widgets\LinkPager;
use app\modules\schoolcore\models\CoreTerm;
use app\modules\planner\models\CoreStaff;
use app\models\User;
use app\modules\dissertation\models\Dissertation;


/* @var $this yii\web\View */
/* @var $model app\models\Classes */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Classes', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

$staffInfo = empty($model->supervisor) ? '' : CoreStaff::findOne($model->supervisor);
$supervisor = $staffInfo ? $staffInfo->first_name . ' ' . $staffInfo->last_name : '';

?>


<div class="row ">
    <div class="col-md-12">
        <h3><i class="fa fa-plus"></i> <?= ($model->title) ? $model->title : "--" ?></h3>
        <hr class="l_header"></hr>
        <div class="col-md-12">
            <br/>
            <br/>
        </div>
    </div>

    <?php if (( $model->supervisor == Yii::$app->user->identity->id || $model->created_by == Yii::$app->user->identity->id)): ?>


    <div class="col-md-12">
        <div class="pull-right">

            <?php if (!Yii::$app->user->can('non_student') && !$model->approved) : ?>
                <?= Html::a('<i class="fa fa-edit" >Update</i>', ['update', 'id' => $model->id], ['class' => 'btn btn-sm btn-primary']) ?>
                <?= Html::a('<i class="fa fa-trash" >Delete</i>', ['delete', 'id' => $model->id], [
                    'class' => 'btn btn-sm btn-danger',
                    'data' => [
                        'confirm' => 'Are you sure you want to delete this dissertation?',
                        'method' => 'post',
                    ],
                ]) ?>
            <?php endif; ?>




        </div>
    </div>


    <br><br>

    <div class="col-md-12 ">
        <div class="row">
            <div class="col-md-12 ">
                <div class="col-md-3" style="background: #F0F3FF; padding:10px;margin-bottom: 5px;">Status</div>
                <div class="col-md-6"
                     style="background: #fff; padding:10px"><?= ($model->status) ? $model->status : ' --' ?></div>
            </div>
            <hr>
            <hr class="l_header">

            <div class="col-md-12 ">
                <div class="col-md-3" style="background: #F0F3FF; padding:10px;margin-bottom: 5px;">Uploaded By</div>
                <div class="col-md-6"
                     style="background: #fff; padding:10px"><?= $model->created_by ? User::findOne($model->created_by)->username : "--" ?></div>
            </div>
            <div class="col-md-12 ">
                <div class="col-md-3" style="background: #F0F3FF; padding:10px;margin-bottom: 5px;">Student Name</div>
                <div class="col-md-6"
                     style=" background: #fff;padding:10px"><?= ($model->student_id) ? $model->stdName->first_name .' '. $model->stdName->last_name: ' --' ?></div>
            </div>
            <hr class="l_header">
            <div class="col-md-12">
                <div class="col-md-3" style="background: #F0F3FF; padding:10px;margin-bottom: 5px;">Department</div>
                <div class="col-md-6"
                     style="background: #fff; padding:10px"><?= ($model->department) ? $model->department : ' --' ?></div>
            </div>
            <hr class="l_header">
            <div class="col-md-12">
                <div class="col-md-3" style="background: #F0F3FF; padding:10px;margin-bottom: 5px;">Degree Program</div>
                <div class="col-md-6"
                     style="background: #fff; padding:10px"><?= ($model->degree_program) ? $model->degree_program : ' --' ?></div>
            </div>
            <hr class="l_header">
        </div>
        <div class="row">
            <div class="col-md-12 ">
                <div class="col-md-3" style="background: #F0F3FF; padding:10px;margin-bottom: 5px;">Summary/Abstract
                </div>
                <div class="col-md-6"
                     style="background: #fff; padding:10px"><?= ($model->summary) ? $model->summary : ' --' ?></div>
            </div>
            <div class="col-md-12 ">
                <div class="col-md-3" style="background: #F0F3FF; padding:10px;margin-bottom: 5px;">Supervisor</div>
                <div class="col-md-6"
                     style="background: #fff; padding:10px"><?= ($model->supervisor) ? $supervisor : ' --' ?></div>
            </div>
            <hr class="l_header">
        </div>

        <div class="row">
            <div class="col-md-12 ">
                <div class="col-md-3" style="background: #F0F3FF; padding:10px;margin-bottom: 5px;">Submission Date
                </div>
                <div class="col-md-6"
                     style="background: #fff; padding:10px"><?= ($model->submission_date) ? date('Y-m-d', strtotime($model->submission_date)) : ' --' ?></div>
            </div>
            <div class="col-md-12 ">
                <div class="col-md-3" style="background: #F0F3FF; padding:10px;margin-bottom: 5px;">Uploaded By</div>
                <div class="col-md-6"
                     style="background: #fff; padding:10px"><?= $model->created_by ? User::findOne($model->created_by)->username : "--" ?></div>
            </div>

            <?php if ($model->approved) : ?>

                <div class="col-md-12 ">
                    <div class="col-md-3" style="background: #F0F3FF; padding:10px;margin-bottom: 5px;">Uploaded By</div>
                    <div class="col-md-6"
                         style="background: #fff; padding:10px"><?= $model->approved ? 'APPROVED' : "REJECTED" ?></div>
                </div>
            <?php endif;?>


            <hr class="l_header">
        </div>

        <br>
    </div>
    <div class="col-md-12 ">
        <?php if ($model->storedFiles): ?>
            <!-- <div class="col-sm-12 text-center"><h3><i class="fa fa-check-square-o"></i>&nbsp;Attach Supporting Documents</h3></div> -->
            <?= $this->render('files_list', ['uploads' => $model->storedFiles, 'model'=>$model]); ?>
        <?php endif; ?>
    </div>
    <div class="col-md-12 ">
    <?php if (Yii::$app->user->can('approve_dissertation') && !$model->approved) : ?>
        <?= $this->render('_approval_buttons', ['actionModel' => $model]); ?>


    <?php endif; ?>
    </div>

</div>
<?php elseif(( $model->supervisor != Yii::$app->user->identity->id|| $model->created_by != Yii::$app->user->identity->id)): ?>
    <p>No rights to view this Dissertation</p>
<?php endif; ?>